// Pre-Meeting Brief — rebuilt against the register (2026-08-07). Layout
// authority: docs/design/Pre-Meeting Brief.dc.html (claude.ai/design "Rising
// star profile redesign" sibling project). This was the last old-generation
// surface on the demo path — Inter, rounded cards, blue/violet/green citation
// chips, a yellow filled button — and it now composes like the profile spines:
// PageHero masthead with a right-field stats cluster, g2 board with g1 wells,
// mono section labels with gold ticks, priority read by WEIGHT not by pill,
// and the citation chips replaced by a mono-labelled provenance table.
//
// Reading-mode rule, third application (after the asset monograph and
// Positions): the opportunity body is long-dwell serif prose, so it takes
// WARM ink at a 68ch measure. Everything else on the surface is scanned and
// stays on the COOL ramp.
//
// "Generated by Claude" is provenance, not a credit line: the section carries
// MODEL-GENERATED · EVERY CLAIM ATTRIBUTABLE TO A CITED SOURCE · NO CLINICAL
// RECOMMENDATION (the three load-bearing clauses — the frame's five-clause
// line is trimmed; REVIEW BEFORE USE moves to the list footer).
//
// Frame corrections applied:
//   1. Belief rows carry the word STANDING in the date column — a belief is a
//      standing position, undated by nature; a bare em-dash would read as a
//      data gap. (Collaborators: ON RECORD; publications: INDEXED; follow-ups:
//      OPEN; insights: CAPTURED — the payload does not carry per-evidence
//      dates; wiring occurred_at through generate-brief is a payload change.)
//   2. Provenance line trimmed to the three load-bearing clauses (above).
//   3. The layout is count-driven: any number of opportunities renders, and a
//      brief whose citations are all beliefs states that in RECENT INSIGHTS
//      rather than rendering an empty block. No figure is stated that the
//      payload cannot support.

import { Fragment, useCallback, useEffect, useState, type CSSProperties, type ReactNode } from "react";
import { useParams } from "react-router-dom";
import { generateBrief, type Brief, type Opportunity, type OpportunityEvidence, type Priority } from "../../lib/briefs";
import { createNextAction, type Priority as FollowUpPriority } from "../../lib/relationships";
import AppLayout from "../AppLayout";
import PageHero from "../PageHero";
import { FONT, GROUND, LINE, GOLD, COOL, WARM } from "../../lib/designTokens";
import { useIsDesktop } from "../../lib/useIsDesktop";

const CARD = GROUND.g1; // g1 well inside the g2 board (Commit C)
const CARD_EDGE = LINE.l1;
const RULE = LINE.l0;
const MONO = FONT.mono;
const SERIF = FONT.serif;

const mono = (size: number, color: string, ls = 0.12, weight = 400): CSSProperties => ({
  font: `${weight} ${size}px/1.5 ${MONO}`, letterSpacing: `${ls}em`, color,
});
const serif = (size: number, color: string, lh = 1.6): CSSProperties => ({
  font: `400 ${size}px/${lh} ${SERIF}`, color,
});

// Priority reads by WEIGHT, never by pill: ink step + weight + tracking carry it.
const PRIORITY_STYLE: Record<Priority, CSSProperties> = {
  high: { font: `600 9.5px/1.4 ${MONO}`, letterSpacing: ".22em", color: COOL.ui },
  medium: { font: `500 9.5px/1.4 ${MONO}`, letterSpacing: ".22em", color: COOL.chrome },
  low: { font: `400 9.5px/1.4 ${MONO}`, letterSpacing: ".22em", color: COOL.label },
};
const PRIORITY_ORDER: Record<Priority, number> = { high: 0, medium: 1, low: 2 };

// Provenance-table vocabulary. The date column never renders an em-dash: where
// no date exists (or the payload does not carry one) the row states its nature.
const EVIDENCE_TYPE_LABEL: Record<string, string> = {
  insight: "FIELD INSIGHT",
  follow_up: "FOLLOW-UP",
  publication: "PUBLICATION",
  theme: "BELIEF",
  collaborator: "COLLABORATOR",
};
const EVIDENCE_STATE_WORD: Record<string, string> = {
  insight: "CAPTURED",
  follow_up: "OPEN",
  publication: "INDEXED",
  theme: "STANDING", // correction 1 — a belief is a standing position, undated by nature
  collaborator: "ON RECORD",
};

function evidenceCountLine(evidence: OpportunityEvidence[]): string {
  const counts = new Map<string, number>();
  for (const e of evidence) counts.set(e.type, (counts.get(e.type) ?? 0) + 1);
  const noun: Record<string, [string, string]> = {
    insight: ["FIELD INSIGHT", "FIELD INSIGHTS"],
    follow_up: ["FOLLOW-UP", "FOLLOW-UPS"],
    publication: ["PUBLICATION", "PUBLICATIONS"],
    theme: ["BELIEF", "BELIEFS"],
    collaborator: ["COLLABORATOR RECORD", "COLLABORATOR RECORDS"],
  };
  const parts: string[] = [];
  for (const [t, n] of counts) parts.push(`${n} ${noun[t] ? noun[t][n === 1 ? 0 : 1] : t.toUpperCase()}`);
  return parts.join(" · ") || "NO CITED SOURCES";
}

function fmtGenerated(iso: string): string {
  const d = new Date(iso);
  const date = d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
  const time = d.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit", hour12: false });
  return `GENERATED ${date.toUpperCase()} · ${time}`;
}

function fmtShortDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

function dueDateFromPriority(priority: Priority): string {
  const now = new Date();
  const daysAhead = priority === "high" ? 7 : priority === "medium" ? 14 : 30;
  const due = new Date(now);
  due.setDate(due.getDate() + daysAhead);
  due.setUTCHours(12, 0, 0, 0);
  return due.toISOString();
}
const FOLLOWUP_PRIORITY: Record<Priority, FollowUpPriority> = { high: "high", medium: "normal", low: "low" };

function SectionHead({ title, right }: { title: string; right?: ReactNode }) {
  return (
    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", gap: 12, paddingBottom: 8, borderBottom: `1px solid ${CARD_EDGE}` }}>
      <div style={{ display: "flex", alignItems: "center", gap: 9 }}>
        <div style={{ width: 2, height: 9, background: GOLD.gold }} />
        <span style={mono(9.5, GOLD.gold, 0.2, 500)}>{title}</span>
      </div>
      {right ? <span style={mono(8.5, COOL.label, 0.15)}>{right}</span> : null}
    </div>
  );
}

// SAVE AS FOLLOW-UP — outline, gold, never filled (the frame's tinted well is
// dropped for the register's transparent outline treatment).
function SaveFollowUp({ opportunity, hcpId, userId, saved, onSaved }: {
  opportunity: Opportunity; hcpId: string; userId: string; saved: boolean; onSaved: () => void;
}) {
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleSave() {
    if (pending || saved) return;
    setPending(true);
    setError(null);
    try {
      await createNextAction(userId, {
        hcpId,
        body: opportunity.recommendation,
        dueAt: dueDateFromPriority(opportunity.priority),
        priority: FOLLOWUP_PRIORITY[opportunity.priority],
        createdFrom: "brief",
      });
      onSaved();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Save failed");
    } finally {
      setPending(false);
    }
  }

  return (
    <div style={{ padding: "0 20px 17px", display: "flex", justifyContent: "flex-end", alignItems: "baseline", gap: 12 }}>
      {error ? <span style={mono(8.5, COOL.muted, 0.06)}>{error}</span> : null}
      <button
        onClick={() => void handleSave()}
        disabled={pending || saved}
        style={{
          border: `1px solid ${saved ? LINE.l2 : GOLD.dim}`, background: "transparent",
          padding: "7px 15px", cursor: pending || saved ? "default" : "pointer", minHeight: 0,
          font: `500 8.5px/1.4 ${MONO}`, letterSpacing: ".19em", textTransform: "uppercase",
          color: saved ? COOL.label : GOLD.gold, opacity: pending ? 0.6 : 1,
        }}
      >
        {saved ? "Saved as follow-up" : pending ? "Saving…" : "Save as follow-up"}
      </button>
    </div>
  );
}

function OpportunityCard({ opportunity, index, hcpId, userId, saved, onSaved }: {
  opportunity: Opportunity; index: number; hcpId: string; userId: string; saved: boolean; onSaved: () => void;
}) {
  const n = String(index + 1).padStart(2, "0");
  return (
    <div style={{ border: `1px solid ${CARD_EDGE}`, background: CARD }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, padding: "13px 20px", borderBottom: `1px solid ${RULE}`, flexWrap: "wrap" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 13 }}>
          <span style={{ font: `400 14px/1 ${SERIF}`, color: GOLD.dim }}>{n}</span>
          <span style={mono(9, GOLD.gold, 0.19, 500)}>{opportunity.category}</span>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 9 }}>
          <span style={mono(8, COOL.label, 0.15)}>PRIORITY</span>
          <span style={{ ...PRIORITY_STYLE[opportunity.priority], textTransform: "uppercase" }}>{opportunity.priority}</span>
        </div>
      </div>

      {/* long-dwell prose — WARM ink at a reading measure (reading-mode rule) */}
      <div style={{ padding: "20px 20px 4px" }}>
        <p style={{ font: `400 16.5px/1.7 ${SERIF}`, color: WARM.prose, margin: 0, maxWidth: "68ch", textWrap: "pretty" as const }}>
          {opportunity.recommendation}
        </p>
      </div>

      {/* BASED ON — the provenance table that replaces the coloured chips */}
      <div style={{ padding: "17px 20px 18px" }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", gap: 10, paddingBottom: 7, borderBottom: `1px solid ${RULE}` }}>
          <span style={mono(8, GOLD.gold, 0.22)}>BASED ON</span>
          <span style={mono(8, COOL.label, 0.15)}>{evidenceCountLine(opportunity.supporting_evidence)}</span>
        </div>
        {opportunity.supporting_evidence.length ? (
          <div style={{ display: "grid", gridTemplateColumns: "104px 86px minmax(0,1fr)", gap: "0 16px", alignItems: "baseline" }}>
            {opportunity.supporting_evidence.map((e, i) => (
              <Fragment key={i}>
                <div style={{ paddingTop: i === 0 ? 11 : 8, ...mono(8, COOL.label, 0.15) }}>{EVIDENCE_TYPE_LABEL[e.type] ?? e.type.toUpperCase()}</div>
                <div style={{ paddingTop: i === 0 ? 11 : 8, ...mono(8, COOL.faint, 0.11) }}>{EVIDENCE_STATE_WORD[e.type] ?? "ON RECORD"}</div>
                <div style={{ paddingTop: i === 0 ? 11 : 8, ...serif(14, COOL.chromeStrong, 1.5) }}>{e.label}</div>
              </Fragment>
            ))}
          </div>
        ) : (
          <div style={{ paddingTop: 11, ...mono(8.5, COOL.label, 0.12) }}>
            NO CITED SOURCES ON THIS OPPORTUNITY — TREAT AS DIRECTION, NOT EVIDENCE
          </div>
        )}
      </div>

      <SaveFollowUp opportunity={opportunity} hcpId={hcpId} userId={userId} saved={saved} onSaved={onSaved} />
    </div>
  );
}

// ── Right rail — mono-labelled panels one step above the ground, the same
//    treatment as the profile spines' rails. Every section carries an honest
//    absence state; nothing renders blank.
function RailPanel({ title, count, children }: { title: string; count?: string; children: ReactNode }) {
  return (
    <div>
      <SectionHead title={title} right={count} />
      <div style={{ border: `1px solid ${CARD_EDGE}`, background: CARD, padding: "4px 16px 14px", marginTop: 10 }}>
        {children}
      </div>
    </div>
  );
}

function RailRow({ label, value, serifValue = false }: { label: string; value: ReactNode; serifValue?: boolean }) {
  return (
    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", gap: 14, paddingTop: 10 }}>
      <span style={mono(8, COOL.label, 0.15)}>{label}</span>
      <span style={serifValue ? { ...serif(13, COOL.chromeStrong, 1.4), textAlign: "right" as const } : { ...mono(8.5, COOL.chrome, 0.12), textAlign: "right" as const }}>
        {value}
      </span>
    </div>
  );
}

export default function BriefPage() {
  const { id: hcpId } = useParams(); // standardized to :id across /hcp routes (stage-4 cutover)
  const isDesktop = useIsDesktop();
  const [brief, setBrief] = useState<Brief | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [savedIndices, setSavedIndices] = useState<Set<number>>(new Set());

  const loadBrief = useCallback(async (id: string) => {
    setLoading(true);
    setError(null);
    try {
      const result = await generateBrief(id);
      setBrief(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error");
      setBrief(null);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    if (!hcpId) {
      setError("HCP ID missing");
      setLoading(false);
      return;
    }
    void loadBrief(hcpId);
  }, [hcpId, loadBrief]);

  const breadcrumbs = brief?.content.hcp
    ? [
        { label: "Home", path: "/me" },
        { label: brief.content.hcp.name, path: hcpId ? `/hcp/${hcpId}` : undefined },
        { label: "Brief" },
      ]
    : [
        { label: "Home", path: "/me" },
        { label: "Brief" },
      ];

  if (loading) {
    return (
      <AppLayout breadcrumbs={breadcrumbs} width="wide">
        <style>{`@keyframes briefPulse { 0%, 100% { opacity: 0.4; } 50% { opacity: 0.85; } }`}</style>
        <div style={{ padding: "48px 0", animation: "briefPulse 2s ease-in-out infinite", ...mono(10.5, COOL.muted, 0.08) }}>
          ASSEMBLING THE BRIEF — SYNTHESIS OVER THE CITED RECORD…
        </div>
      </AppLayout>
    );
  }

  if (error || !brief) {
    return (
      <AppLayout breadcrumbs={breadcrumbs} width="wide">
        <div style={{ padding: "48px 0", display: "flex", flexDirection: "column", gap: 12, alignItems: "flex-start" }}>
          <div style={mono(11, COOL.ui, 0.12, 500)}>THE BRIEF COULD NOT BE GENERATED</div>
          <div style={{ ...serif(13.5, COOL.muted), maxWidth: 620 }}>{error ?? "Empty response."}</div>
          <button onClick={() => hcpId && void loadBrief(hcpId)}
            style={{ border: `1px solid ${GOLD.dim}`, background: "transparent", padding: "7px 15px", cursor: "pointer", minHeight: 0, font: `500 8.5px/1.4 ${MONO}`, letterSpacing: ".19em", color: GOLD.gold, textTransform: "uppercase" }}>
            Retry
          </button>
        </div>
      </AppLayout>
    );
  }

  const { hcp, insights, follow_ups, publications, themes, collaborators, relationship } = brief.content;
  // ordered by weight (correction 3: count-driven — any number of cards renders)
  const opportunities = (brief.content.opportunities ?? [])
    .slice()
    .sort((a, b) => PRIORITY_ORDER[a.priority] - PRIORITY_ORDER[b.priority]);
  const sourceCount = opportunities.length
    ? opportunities.reduce((s, o) => s + o.supporting_evidence.length, 0)
    : insights.length + themes.length + collaborators.length;
  const lastContact = insights.length
    ? fmtShortDate(insights.slice().sort((a, b) => b.occurred_at.localeCompare(a.occurred_at))[0].occurred_at)
    : null;
  const overdue = follow_ups.filter((f) => f.overdue).length;
  const dekLead = [hcp.specialty, hcp.institution].filter(Boolean).join(" · ");
  const dek = opportunities.length
    ? `${dekLead}. ${opportunities.length} engagement ${opportunities.length === 1 ? "opportunity" : "opportunities"}, each traced to the field insight or stated belief that produced it.`
    : `${dekLead}. Opportunity generation did not complete for this run — the cited record below still stands.`;

  const rail = (
    <div style={{ display: "flex", flexDirection: "column", gap: 26 }}>
      <RailPanel title="RELATIONSHIP CONTEXT">
        <RailRow label="STATUS" value={
          <span style={mono(9, relationship.exists ? COOL.ui : GOLD.gold, 0.18)}>
            {(relationship.status ?? "COLD · NOT ENGAGED").replace(/_/g, " ").toUpperCase()}
          </span>} />
        <RailRow label="LAST CONTACT" value={lastContact ?? "NONE ON RECORD"} />
        <RailRow label="OPEN FOLLOW-UPS" value={`${follow_ups.length}${overdue ? ` · ${overdue} OVERDUE` : ""}`} />
        <RailRow label="AFFILIATION" value={hcp.institution || "NOT ON RECORD"} serifValue />
      </RailPanel>

      <RailPanel title="RECENT INSIGHTS" count={String(insights.length)}>
        {insights.length ? insights.slice(0, 5).map((ins, i) => (
          <div key={i} style={{ padding: "13px 0 0", borderBottom: i < Math.min(insights.length, 5) - 1 ? `1px solid ${RULE}` : "none", paddingBottom: i < Math.min(insights.length, 5) - 1 ? 13 : 0 }}>
            <div style={{ display: "flex", justifyContent: "space-between", gap: 10, marginBottom: 7 }}>
              <span style={mono(8, COOL.label, 0.15)}>{ins.interaction_type.replace(/_/g, " ").toUpperCase()} · {ins.insight_strength.replace(/_/g, " ").toUpperCase()}</span>
              <span style={mono(8, COOL.label, 0.15)}>{fmtShortDate(ins.occurred_at)}</span>
            </div>
            <div style={serif(13.5, COOL.chromeStrong, 1.55)}>
              {ins.body.length > 150 ? `${ins.body.slice(0, 150).trimEnd()}…` : ins.body}
            </div>
          </div>
        )) : (
          // correction 3 — the belief-only brief names the absence rather than
          // rendering an empty block
          <div style={{ paddingTop: 12, ...mono(8.5, COOL.label, 0.14), lineHeight: 1.9 }}>
            NO FIELD INSIGHTS CAPTURED — THE BRIEF DRAWS ON STATED BELIEFS AND THE PUBLISHED RECORD
          </div>
        )}
      </RailPanel>

      <RailPanel title="BELIEF PROFILES" count={String(themes.length)}>
        {themes.length ? themes.map((t, i) => (
          <div key={t} style={{ padding: "10px 0 0", borderBottom: i < themes.length - 1 ? `1px solid ${RULE}` : "none", paddingBottom: i < themes.length - 1 ? 10 : 0, ...serif(13.5, COOL.chromeStrong, 1.45) }}>
            {t}
          </div>
        )) : (
          <div style={{ paddingTop: 12, ...mono(8.5, COOL.label, 0.14), lineHeight: 1.9 }}>NO BELIEF PROFILES ON FILE</div>
        )}
      </RailPanel>

      <RailPanel title="SCIENTIFIC ACTIVITY" count={publications.length ? String(publications.length) : undefined}>
        {publications.length ? publications.slice(0, 5).map((pub, i) => (
          <div key={i} style={{ padding: "11px 0 0", borderBottom: i < Math.min(publications.length, 5) - 1 ? `1px solid ${RULE}` : "none", paddingBottom: i < Math.min(publications.length, 5) - 1 ? 11 : 0 }}>
            <div style={serif(13.5, COOL.chromeStrong, 1.45)}>{pub.title}</div>
            <div style={{ marginTop: 5, ...mono(8, COOL.label, 0.13) }}>{pub.year}</div>
          </div>
        )) : (
          <div style={{ paddingTop: 12, ...mono(8.5, COOL.label, 0.14), lineHeight: 1.9 }}>
            NO RECENT PUBLICATIONS INDEXED · LAST INGEST {fmtGenerated(brief.generated_at).replace("GENERATED ", "")}
          </div>
        )}
      </RailPanel>

      <RailPanel title="TOP COLLABORATORS" count={String(collaborators.length)}>
        {collaborators.length ? collaborators.map((c, i) => (
          <div key={c.name} style={{ padding: "11px 0 0", borderBottom: i < collaborators.length - 1 ? `1px solid ${RULE}` : "none", paddingBottom: i < collaborators.length - 1 ? 11 : 0 }}>
            <div style={serif(14.5, COOL.prose, 1.35)}>{c.name}</div>
            {c.institution ? <div style={{ marginTop: 5, ...mono(8, COOL.label, 0.13) }}>{c.institution.toUpperCase()}</div> : null}
          </div>
        )) : (
          <div style={{ paddingTop: 12, ...mono(8.5, COOL.label, 0.14), lineHeight: 1.9 }}>NO COLLABORATOR RECORDS HELD</div>
        )}
      </RailPanel>
    </div>
  );

  const main = (
    <div style={{ minWidth: 0 }}>
      <SectionHead title="STRATEGIC ENGAGEMENT OPPORTUNITIES"
        right={opportunities.length ? `${opportunities.length} · ORDERED BY WEIGHT` : "NONE GENERATED"} />
      {/* correction 2 — the three load-bearing clauses; the rest moved or dropped */}
      <div style={{ padding: "11px 0 0", ...mono(8, COOL.label, 0.15), lineHeight: 2 }}>
        MODEL-GENERATED · EVERY CLAIM ATTRIBUTABLE TO A CITED SOURCE · NO CLINICAL RECOMMENDATION
      </div>

      {opportunities.length ? (
        <div style={{ display: "flex", flexDirection: "column", gap: 16, marginTop: 20 }}>
          {opportunities.map((opp, i) => (
            <OpportunityCard key={i} opportunity={opp} index={i} hcpId={brief.hcp_id} userId={brief.user_id}
              saved={savedIndices.has(i)} onSaved={() => setSavedIndices((s) => new Set(s).add(i))} />
          ))}
        </div>
      ) : (
        <div style={{ marginTop: 20, border: `1px solid ${CARD_EDGE}`, background: CARD, padding: "20px 22px" }}>
          <div style={mono(11, COOL.muted, 0.12, 500)}>
            {brief.ai_status === "failed" ? "OPPORTUNITY GENERATION FAILED FOR THIS RUN" : "NO OPPORTUNITIES GENERATED FOR THIS RUN"}
          </div>
          <div style={{ marginTop: 12, ...serif(13.5, COOL.chromeStrong), maxWidth: "68ch" }}>
            {brief.ai_error
              ? `The synthesis step reported: ${brief.ai_error}. The cited record in the rail is unaffected — it is read directly, not generated.`
              : "The cited record in the rail is unaffected — it is read directly, not generated. Regenerate to retry the synthesis step."}
          </div>
        </div>
      )}

      <div style={{ marginTop: 22, paddingTop: 11, borderTop: `1px solid ${CARD_EDGE}`, ...mono(8, COOL.label, 0.15), lineHeight: 2 }}>
        REVIEW BEFORE USE
      </div>
    </div>
  );

  return (
    <AppLayout breadcrumbs={breadcrumbs} width="wide">
      <div style={{ fontFamily: MONO, margin: "8px 0 24px", padding: "28px 36px 40px", background: GROUND.g2, border: `1px solid ${LINE.l1}` }}>
        <div style={{ padding: "6px 0 24px", borderBottom: `1px solid ${CARD_EDGE}` }}>
          <PageHero
            narrow={!isDesktop}
            eyebrow="Pre-Meeting Brief"
            meta={fmtGenerated(brief.generated_at)}
            title={hcp.name}
            dek={dek}
            stats={{ variant: "cluster", items: [
              { value: hcp.score != null ? hcp.score.toFixed(1) : "—", label: "SCORE", gold: true },
              { value: hcp.rank != null ? `#${hcp.rank}` : "—", label: "RANK · US" },
              { value: String(opportunities.length), label: "OPPORTUNITIES" },
              { value: String(sourceCount), label: "SOURCES CITED" },
            ] }}
          />
        </div>

        {isDesktop ? (
          <div style={{ display: "grid", gridTemplateColumns: "minmax(0,1fr) 320px", gap: 30, marginTop: 32, alignItems: "start" }}>
            {main}
            {rail}
          </div>
        ) : (
          <div style={{ display: "flex", flexDirection: "column", gap: 30, marginTop: 28 }}>
            {main}
            {rail}
          </div>
        )}
      </div>
    </AppLayout>
  );
}
