import { useCallback, useState } from "react";
import type { AiStatus, Opportunity } from "../../lib/briefs";
import OpportunityCard from "./OpportunityCard";

interface Props {
  opportunities: Opportunity[] | null;
  aiStatus: AiStatus;
  aiError: string | null;
  hcpId: string;
  userId: string;
}

const sectionHeaderStyle = {
  fontSize: 11,
  color: "#6B6A65",
  textTransform: "uppercase" as const,
  letterSpacing: "0.06em",
  fontWeight: 500,
  marginBottom: 4,
};

export default function StrategicOpportunities({
  opportunities,
  aiStatus,
  aiError,
  hcpId,
  userId,
}: Props) {
  const [savedIndices, setSavedIndices] = useState<Set<number>>(new Set());

  const markSaved = useCallback((index: number) => {
    setSavedIndices((prev) => {
      const next = new Set(prev);
      next.add(index);
      return next;
    });
  }, []);

  const showOpportunities =
    aiStatus === "generated" && opportunities != null && opportunities.length > 0;

  return (
    <div style={{ fontFamily: "system-ui, -apple-system, sans-serif" }}>
      <div style={sectionHeaderStyle}>STRATEGIC ENGAGEMENT OPPORTUNITIES</div>
      <div style={{ fontSize: 10, color: "#6B6A65", marginBottom: 16 }}>Generated by Claude</div>

      {showOpportunities ? (
        <div>
          {opportunities!.map((opportunity, index) => (
            <OpportunityCard
              key={index}
              opportunity={opportunity}
              index={index}
              hcpId={hcpId}
              userId={userId}
              isSaved={savedIndices.has(index)}
              onSaved={() => markSaved(index)}
            />
          ))}
        </div>
      ) : (
        <div>
          <div style={{ fontSize: 13, color: "#6B6A65", lineHeight: 1.5 }}>
            Strategic Engagement Opportunities unavailable. Please try again.
          </div>
          {aiError && aiStatus === "failed" ? (
            <div style={{ fontSize: 11, color: "#6B6A65", marginTop: 8, lineHeight: 1.4 }}>
              {aiError}
            </div>
          ) : null}
        </div>
      )}
    </div>
  );
}
