-- ============================================================================
-- One-shot backfill: Atopic Dermatitis PubMed ingest (June 10, 2026)
--
-- Fixes publications_v2 rows that landed with NULL source_therapeutic_area_id
-- and missing publication_therapeutic_areas_v2 join rows.
--
-- AD therapeutic_area_id: 9e4139d2-e062-4a58-8728-cdabb2d7dca1
--
-- PMID set (choose ONE method below):
--   A) Canonical — load from pubmed checkpoint JSON (recommended, exact match
--      to tonight's ESearch result). See PowerShell block at bottom of file.
--   B) Derived — CTE proxy if checkpoint file is unavailable (should be ~14.9k
--      rows: pubmed-sourced pubs with NULL source_ta and AD-tagged authors).
--
-- Run entire script in one Supabase SQL editor session (temp table scope).
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- Step 0: Build ad_pubmed_pmids temp table
-- ----------------------------------------------------------------------------

CREATE TEMP TABLE ad_pubmed_pmids (
  pubmed_id text PRIMARY KEY
);

-- METHOD A (recommended): uncomment after populating from checkpoint.
-- Paste INSERT rows generated by the PowerShell snippet at the bottom, e.g.:
--   INSERT INTO ad_pubmed_pmids (pubmed_id) VALUES
--     ('12345678'),
--     ('23456789');
--   -- ... one row per PMID from checkpoint phases.pmid_retrieval.pmids

-- METHOD B (fallback): derived PMID set from tonight's ingest footprint.
-- Comment out if using Method A.
INSERT INTO ad_pubmed_pmids (pubmed_id)
SELECT DISTINCT p.pubmed_id
FROM publications_v2 p
JOIN publication_authors_v2 pa ON pa.publication_id = p.id
JOIN hcp_therapeutic_areas_v2 hta
  ON hta.hcp_id = pa.hcp_id
 AND hta.therapeutic_area_id = '9e4139d2-e062-4a58-8728-cdabb2d7dca1'::uuid
WHERE p.pubmed_id IS NOT NULL
  AND p.source = 'pubmed'
  AND p.source_therapeutic_area_id IS NULL
ON CONFLICT (pubmed_id) DO NOTHING;

-- Sanity check before mutating
SELECT COUNT(*) AS ad_pmid_count FROM ad_pubmed_pmids;

-- ----------------------------------------------------------------------------
-- Operation 1: Backfill source_therapeutic_area_id on publications_v2
-- ----------------------------------------------------------------------------

UPDATE publications_v2 p
SET source_therapeutic_area_id = '9e4139d2-e062-4a58-8728-cdabb2d7dca1'::uuid
FROM ad_pubmed_pmids a
WHERE p.pubmed_id = a.pubmed_id
  AND p.source_therapeutic_area_id IS NULL;

-- ----------------------------------------------------------------------------
-- Operation 2: Insert publication_therapeutic_areas_v2 join rows
-- ----------------------------------------------------------------------------

INSERT INTO publication_therapeutic_areas_v2 (
  publication_id,
  therapeutic_area_id,
  source
)
SELECT
  p.id,
  '9e4139d2-e062-4a58-8728-cdabb2d7dca1'::uuid,
  'pubmed'
FROM publications_v2 p
JOIN ad_pubmed_pmids a ON a.pubmed_id = p.pubmed_id
ON CONFLICT (publication_id, therapeutic_area_id) DO NOTHING;

COMMIT;

-- ----------------------------------------------------------------------------
-- Verification
-- ----------------------------------------------------------------------------

-- 1) PMID set size used for backfill (re-create temp table if session ended)
--    For post-commit verification, use the derived filter directly:

SELECT
  COUNT(DISTINCT p.pubmed_id) AS ad_pubmed_pmids_in_scope,
  COUNT(DISTINCT p.id) FILTER (
    WHERE p.source_therapeutic_area_id = '9e4139d2-e062-4a58-8728-cdabb2d7dca1'::uuid
  ) AS pubs_with_source_ta_set,
  COUNT(DISTINCT p.id) FILTER (
    WHERE p.source_therapeutic_area_id IS NULL
  ) AS pubs_still_null_source_ta,
  COUNT(DISTINCT pta.publication_id) AS pubs_with_pub_ta_join
FROM publications_v2 p
JOIN publication_authors_v2 pa ON pa.publication_id = p.id
JOIN hcp_therapeutic_areas_v2 hta
  ON hta.hcp_id = pa.hcp_id
 AND hta.therapeutic_area_id = '9e4139d2-e062-4a58-8728-cdabb2d7dca1'::uuid
LEFT JOIN publication_therapeutic_areas_v2 pta
  ON pta.publication_id = p.id
 AND pta.therapeutic_area_id = '9e4139d2-e062-4a58-8728-cdabb2d7dca1'::uuid
WHERE p.pubmed_id IS NOT NULL
  AND p.source = 'pubmed';

-- 2) Expected after successful backfill:
--    pubs_still_null_source_ta = 0 (or near 0 if some PMIDs lack publications_v2 rows)
--    pubs_with_pub_ta_join should equal pubs_with_source_ta_set

-- ============================================================================
-- PowerShell: extract canonical PMID list from checkpoint → SQL INSERT
-- (run locally; paste output into METHOD A above, replace METHOD B insert)
--
--   $cp = Get-Content "pubmed_checkpoint_atopic-dermatitis_v2.json" | ConvertFrom-Json
--   # or: pubmed_checkpoint_atopic-dermatitis.json for v1-era checkpoint
--   $pmids = $cp.phases.pmid_retrieval.pmids
--   "INSERT INTO ad_pubmed_pmids (pubmed_id) VALUES"
--   ($pmids | ForEach-Object { "  ('$_')" }) -join ",`n" | Write-Output
--   ";"
-- ============================================================================
